name: dumel-dump

services:
  mysql_db:
    image: mysql
    container_name: dumel-dump-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dumel_db
      MYSQL_USER: dumel_user
      MYSQL_PASSWORD: dumelMysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: dumel-dump-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql_db

volumes:
  mysql_data: